version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- "./reverse-proxy-config/init-letsencrypt:/etc/nginx/conf.d"
      - "./reverse-proxy-config/live:/etc/nginx/conf.d"
      - "./secrets/reverse-proxy:/secrets"
      - "./repositories:/repositories"
      - "./assets:/assets"
      - "cv_dist:/cv_dist"
      - ./data/certbot/conf:/certbot/conf
      - ./data/certbot/html:/certbot/html
    networks:
      - external
      - personal-website
      - certbot
    restart: always
  
  personal-website:
    build: ./repositories/personal-website.git/
    networks:
      - personal-website
    restart: always

  cv:
    build: ./repositories/cv.git/
    volumes:
      - "./repositories:/repositories"
      - "./secrets/cv:/secrets"
      - "cv_dist:/dist"
    environment:
      - MEJSON=/repositories/me.json.git/me.json
      - SIGNATURE_FILE=/secrets/signature.png
    networks:
      - cv
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/html:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h; certbot renew; done;'"
    networks:
      - external
      - certbot

networks:
  external:
    internal: false
  personal-website:
    internal: true
  cv:
    internal: true
  certbot:
    internal: true

volumes:
  cv_dist: