version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
       - "./reverse-proxy-config:/etc/nginx/conf.d"
       - "./secrets/reverse-proxy:/secrets"
       - "./repositories:/repositories"
       - "./assets:/assets"
       - "cv_dist:/cv_dist"
    networks:
      - external
      - personal-website
    restart: always
  
  personal-website:
    build: ./repositories/personal-website.git/
    networks:
      - personal-website
    restart: always

  cv:
    build: ./repositories/cv.git/
    volumes:
      - "./repositories:/repositories"
      - "./secrets/cv:/secrets"
      - "cv_dist:/dist"
    environment:
      - MEJSON=/repositories/me.json.git/me.json
      - SIGNATURE_FILE=/secrets/signature.png
    networks:
      - cv
    restart: always


networks:
  external:
    internal: false
  personal-website:
    internal: true
  cv:
    internal: true

volumes:
  cv_dist: