version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      #- reverse-proxy-config/init-letsencrypt:/etc/nginx/conf.d
      - ./reverse-proxy-config/live:/etc/nginx/conf.d
      - ./secrets/reverse-proxy:/secrets
      - ./repositories:/repositories
      - ./assets:/assets
      - ./pubs:/pubs
      - cv_dist:/cv_dist
      - ./data/certbot/conf:/certbot/conf
      - ./data/certbot/html:/certbot/html
    networks:
      - external
      - personal-website
      - certbot
    restart: always
  
  personal-website:
    build: ./repositories/personal-website-next.git/
    networks:
      - personal-website
      - external
    restart: always

  cv:
    build: ./repositories/cv.git/
    volumes:
      - ./repositories:/repositories
      - ./secrets/cv:/secrets
      - cv_dist:/dist
    environment:
      - MEJSON=/repositories/me.json.git/me.json
      - SIGNATURE_FILE=/secrets/signature.png
    networks:
      - cv
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/html:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h; certbot renew; done;'"
    networks:
      - external
      - certbot

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - nextcloud
    command: --innodb-read-only-compressed=OFF
   
  nextcloud-redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - nextcloud

  nextcloud-app:
    image: nextcloud
    restart: always
    networks:
      - nextcloud
      - external
    volumes:
      - ./nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db

      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}

      - OBJECTSTORE_SWIFT_URL=${OBJECTSTORE_SWIFT_URL}
      - OBJECTSTORE_SWIFT_AUTOCREATE=${OBJECTSTORE_SWIFT_AUTOCREATE}

      - OBJECTSTORE_SWIFT_USER_NAME=${OBJECTSTORE_SWIFT_USER_NAME}
      - OBJECTSTORE_SWIFT_USER_PASSWORD=${OBJECTSTORE_SWIFT_USER_PASSWORD}

      - OBJECTSTORE_SWIFT_PROJECT_NAME=${OBJECTSTORE_SWIFT_PROJECT_NAME}
      - OBJECTSTORE_SWIFT_SERVICE_NAME=${OBJECTSTORE_SWIFT_SERVICE_NAME}
      - OBJECTSTORE_SWIFT_CONTAINER_NAME=${OBJECTSTORE_SWIFT_CONTAINER_NAME}
      - OBJECTSTORE_SWIFT_REGION=${OBJECTSTORE_SWIFT_REGION}


  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
      - nextcloud-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
      - NEXTCLOUD_PROJECT_NAME=galatolome


networks:
  external:
    internal: false
  personal-website:
    internal: true
  cv:
    internal: true
  certbot:
    internal: true
  nextcloud:
    internal: true

volumes:
  cv_dist:
